version: "{build}-{branch}"

# branches to build
branches:
  except:
    - gh-pages

skip_tags: true

os: Visual Studio 2015

platform:
    - X64
    - Win32

configuration:
    - Debug
    - Release

environment:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
    BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\redisclient

build_script:
    - cmd: cd C:\projects\redisclient
    - cmd: md build
    - cmd: cd build
    - ps: |
        If ($env:platform -Match "Win32") {
            $env:CMAKE_GENERATOR_NAME="Visual Studio 14 2015"
            $env:BOOST_LIBRARYDIR=$env:BOOST_LIBRARYDIR_WIN32
        }
    - ps: |
        If ($env:platform -Match "X64") {
            $env:CMAKE_GENERATOR_NAME="Visual Studio 14 2015 Win64"
            $env:BOOST_LIBRARYDIR=$env:BOOST_LIBRARYDIR_WIN64
        }
    - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" -DBUILD_SHARED_LIBS=OFF ..
    - cmd: cmake --build . -- /verbosity:detailed

#test_script:
#   - cmd: ctest -C  %configuration% -VV

